site_name: AeroSim
repo_url: https://github.com/aerosim-open/aerosim
docs_dir: docs
edit_uri: 'edit/master/docs/'
theme: readthedocs
  
nav:
- Home: 'index.md'
- Overview: 'overview.md'
- Getting started:
  - Build AeroSim in Windows: 'build_windows.md'
  - Build AeroSim in Linux: 'build_linux.md'
  - Running a simulation: 'running_aerosim.md'
- Tutorials:
  - First steps: 'first_steps_tutorial.md'
  - Takeoff tutorial: 'takeoff_tutorial.md'
  - Autopilot tutorial: 'autopilot_tutorial.md'
  - ADSB trajectories: 'adsb_trajectories_tutorial.md'
- Examples:
  - First flight: 'example_first_flight.md'
  - Autpilot DAA scenario: 'example_daa.md'
  - Pilot control with fly deck: 'example_pilot.md'
  - Simulink co-simulation and FMU: 'example_simulink.md'
- Resources:
  - AeroSim app: 'aerosim_app.md'
  - Conventions: 'conventions.md'
  - Messages: 'messages.md'
  - Simulation config: 'sim_config.md'
  - FMU reference: 'fmu_reference.md'
  - Scene graph: 'scene_graph_reference.md'
  - Simulink integration: 'simulink_integration.md'
  - SimReady asset creation: 'usd_asset_pipeline.md'
- API reference:
  - aerosim: 'api_aerosim.md'
  - aerosim-data: 'api_aerosim_data.md'
  - aerosim-sensors: 'api_aerosim_sensors.md'
  - aerosim-dynamics-models: 'api_dynamics_models.md'

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
            annotations_path: brief
            show_signature: true
            separate_signature: true
            show_root_toc_entry: false
            show_root_members_full_path: false
            merge_init_into_class: true
            filters:
              - "!^_"

extra_css:
- css/mkdocstrings.css